#### Game Setup

In [81]:
import numpy as np

def print_board(board):
    mapping = {0:'.',1:'o',2:'x'}
    x = list(map(lambda x: mapping[x] if x in mapping else x, board))
    print('\n')
    print(x[0],'|',x[1],'|',x[2])
    print('---------')
    print(x[3],'|',x[4],'|',x[5])
    print('---------')
    print(x[6],'|',x[7],'|',x[8])

    

def generate_random_board():
    return np.random.randint(0,3,(9,))

def permissible_actions(x):
    return np.where(x == 0)[0]


def random_action(x):
    return np.random.choice(permissible_actions(x))

def update_board_p1(board,action_idx):
    board[action_idx] = 1
    return board
  
def update_board_p2(board,action_idx):
    board[action_idx] = 2
    return board

magic_square = np.array([8,1,6,3,5,7,4,9,2])

def check_status(board, player_idx):
    square = magic_square[np.where(board == player_idx, 1,0)]
    square = square.reshape((3,3))
    print(board, square)
    row_sums = np.sum(square, axis=1)
    col_sums = np.sum(square, axis=0)
    diag_sum_1 = np.trace(square)  # Sum of main diagonal
    diag_sum_2 = np.trace(np.fliplr(square))  # Sum of the other diagonal
    if (np.any(row_sums == 15*player_idx)) | (np.any(col_sums == 15*player_idx)) | (diag_sum_1 == 15*player_idx) | (diag_sum_2 == 15*player_idx):
        return player_idx # winner
    elif np.all(board != 0):
        return 0 # draw
    else:
        return 3 # continue

        
    

x = generate_random_board()
print(x)
print_board(x)
check_status(x, 1)

[1 1 0 1 0 1 1 2 2]


o | o | .
---------
o | . | o
---------
o | x | x
[1 1 0 1 0 1 1 2 2] [[1 1 8]
 [1 8 1]
 [1 8 8]]


3

In [491]:
import numpy as np
import random

def print_board(board):
    mapping = {0:'.',1:'o',2:'x'}
    x = list(map(lambda x: mapping[x] if x in mapping else x, board))
    print('\n')
    print(x[0],'|',x[1],'|',x[2])
    print('---------')
    print(x[3],'|',x[4],'|',x[5])
    print('---------')
    print(x[6],'|',x[7],'|',x[8])

def generate_random_board():
    return np.random.randint(0,2,(9,))

def permissible_actions(x):
    return np.where(x == 0)[0]

def random_action(x):
    return np.random.choice(permissible_actions(x))

def update_board(board,action_idx,player_idx):
    board_new = board.copy()
    if player_idx == 0:
        board_new[action_idx] = 1
    else:
        board_new[action_idx] = 2
    return board_new
    
def check_status(board):
    # 0 if player 1 wins, 1 if player 2 wins, 2 if draw, and 3 if incomplete
    status = 3
    board_string = ''.join(map(str, board))
    if '0' not in board_string:
        status = 2
    numbers = ['123','456','789','147','258','369','159','357']
    for number in numbers:
        indices = [int(number[0])-1,int(number[1])-1,int(number[2])-1]
        subset_board = ''.join(board_string[i] for i in indices)
        if subset_board  in ['111']:
            status = 0
        elif subset_board in ['222']:
            status = 1
    return status

def visualize_game(list_x):
    for x in list_x:
        print_board(x[-1])
        
def play_random_game(verbose = 0):
    board = np.array([0,0,0,0,0,0,0,0,0])
    game_history = []
    turn_count = 0
    player_idx = 0
    status = 3
    while True: # incomplete
            
        # check status
        status = check_status(board)
        if status != 3:
            status_final = status
            break
        turn_count += 1
            
        # take random action and update board
        action_idx = random_action(board)
        board_new = update_board(board,action_idx,player_idx)
        game_history.append([board, status, turn_count, player_idx, action_idx, board_new])
        board = board_new.copy()
        
        # switch player
        if player_idx == 0:
            player_idx = 1
        else:
            player_idx = 0
        
    if verbose == 1:
        visualize_game(game_history)
        
    return game_history, status

In [83]:
X = np.random.randint(1, 100, size=(2, 2, 2, 2, 2, 2, 2, 9))
Y = np.array([0, 1, 2, 0, 1, 2, 3])
subset = X[(slice(None),) * len(Y) + tuple(Y)]

IndexError: too many indices for array: array is 8-dimensional, but 14 were indexed

In [493]:
game_history, status = play_random_game(1)
print(status)



. | . | .
---------
. | . | .
---------
. | o | .


. | . | .
---------
. | x | .
---------
. | o | .


. | . | .
---------
. | x | o
---------
. | o | .


. | . | .
---------
x | x | o
---------
. | o | .


. | . | o
---------
x | x | o
---------
. | o | .


. | . | o
---------
x | x | o
---------
x | o | .


o | . | o
---------
x | x | o
---------
x | o | .


o | x | o
---------
x | x | o
---------
x | o | .


o | x | o
---------
x | x | o
---------
x | o | o
0


In [393]:
def simulate_games(N):
    data = [] # board, action, win/loss
    data2 = []
    for i in range(N):
        game_history, status_final = play_random_game()
        for event in game_history:
            board, status, turn_count, player_idx, action_idx, board_new = event
            if status_final == 2:
                score = 0
            elif status_final == player_idx:
                score = +1
            else:
                score = -1
            data.append([i, ''.join(map(str, board)), turn_count, player_idx, action_idx, score, status_final])
        data2.append(status_final)
    return data, data2
    
data, data2  = simulate_games(10000)

In [394]:
pd.DataFrame(data2).value_counts()

0    5888
1    2873
2    1239
dtype: int64

In [395]:
import pandas as pd
df = pd.DataFrame(data, columns = ['Game','Board', 'Turn','Player','Action', 'Score', 'Result'])
df.head()

Game      Board  Turn  Player  Action  Score  Result
0     0  000000000     1       0       8     -1       1
1     0  000000001     2       1       4      1       1
2     0  000020001     3       0       1     -1       1
3     0  010020001     4       1       2      1       1
4     0  012020001     5       0       3     -1       1

In [397]:
df.nunique()

Game      10000
Board      4520
Turn          9
Player        2
Action        9
Score         3
Result        3
dtype: int64

#### Minmax Algorithm

- maximize: find the best value of an action given child states
- minimize: find the lowest value of an action given child states
- terminal node: returns the value of an action

In [506]:
def generate_child(board, player_idx):
    possible_actions = permissible_actions(board)
    childs = []
    for action_idx in possible_actions:
        childs.append(update_board(board, action_idx, player_idx))
        #print_board(update_board(board, action_idx, player_idx))
    return childs
    
def compute_max_value(board, player_idx, initial_node = False):
    
    if player_idx == 0:
        other_player_idx = 1
    else:
        other_player_idx = 0
    status = check_status(board)
    if status == player_idx:
        return +1
    elif status == other_player_idx:
        return -1
    elif status == 2:
        return 0
    else:
        # find child boards
        childs = generate_child(board, player_idx)

        # find max value for opponent
        max_value = np.max([compute_max_value(child, other_player_idx) for child in childs])    
        max_index = np.argmax([compute_max_value(child, other_player_idx) for child in childs])
        
        # what does that mean for you
        if index == False:
            return -max_value
        else:
            return -max_value, permissible_actions(board)[max_index]

In [520]:
compute_max_value(test, 1, True)

(-1, 0)

In [523]:
test = np.array([2,1,2, 0, 0, 1, 0, 1, 2])
print_board(test) # baseline
compute_max_value(test, 1, True)



x | o | x
---------
. | . | o
---------
. | o | x


(1, 3)

In [526]:
test = generate_random_board()
print_board(test)



x | . | .
---------
x | . | .
---------
o | x | x


In [527]:
compute_max_value(test, 0, True)

(-1, 1)

#### Minmax with Alpha-Beta Pruning

In [ ]:
initial_board = np.array([0,0,0,0,0,0,0,0,0])
compute_max_value(initial_board, 0)